import { Container as InjectableDomainPolicy } from "di-framework/decorators";
import type {
  EvaluationResult,
  Issue,
  PullRequest,
} from "../../packages/action-common/src/types.js";

@InjectableDomainPolicy({ singleton: false })
export class EvaluationPolicy {
  findActiveSprint(issues: readonly Issue[]): number | null {
    return findActiveSprint(issues);
  }

  countStalePRs(prs: readonly PullRequest[]): number {
    return countStalePRs(prs);
  }

  evaluate(
    issues: readonly Issue[],
    prs: readonly PullRequest[],
  ): EvaluationResult {
    return evaluate(issues, prs);
  }
}

export function findActiveSprint(issues: readonly Issue[]): number | null {
  const sprints = [...issues].filter((i) =>
    i.labels.some((l) => l.name === "sprint"),
  );
  if (sprints.length === 0) return null;
  // Sub-issues generated by sprint-planning can also carry the `sprint` label,
  // so prefer ones that additionally carry `tracker` — that's the marker for
  // the actual sprint tracker issue whose checklist enumerates the work.
  const trackers = sprints.filter((i) =>
    i.labels.some((l) => l.name === "tracker"),
  );
  const candidates = trackers.length > 0 ? trackers : sprints;
  candidates.sort((a, b) =>
    a.updatedAt < b.updatedAt ? 1 : a.updatedAt > b.updatedAt ? -1 : 0,
  );
  return candidates[0].number;
}

export function countStalePRs(prs: readonly PullRequest[]): number {
  return prs.filter(
    (p) =>
      !p.isDraft &&
      (p.reviewDecision === "CHANGES_REQUESTED" ||
        p.reviewDecision === "REVIEW_REQUIRED"),
  ).length;
}

export function evaluate(
  issues: readonly Issue[],
  prs: readonly PullRequest[],
): EvaluationResult {
  const sprint = findActiveSprint(issues);
  const openIssueCount = issues.length;
  const openPrCount = prs.length;
  const stalePrCount = countStalePRs(prs);

  if (sprint !== null) {
    return {
      route: "work",
      sprint,
      openIssueCount,
      openPrCount,
      stalePrCount,
      tracker: String(sprint),
      reason: `open sprint #${sprint} found; running work dispatch`,
      activeSprint: `#${sprint}`,
    };
  }

  return {
    route: "factory",
    sprint: null,
    openIssueCount,
    openPrCount,
    stalePrCount,
    tracker: "",
    reason: "no open sprint found; running factory cycle",
    activeSprint: "none",
  };
}
